### ISSUE TITLE
Unable to apply PatternLayout DataFluentAppender

### ISSUE THREAD

**Issue by zoosm3** [sndyuk/logback-more-appenders#11]
Hi,

I tried to send hostname to Fluentd using DataFluentAppender. My Logback configuration is as follows:

```
	<appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
		<tag>my-tag</tag>
		<label>my-label</label>
		<remoteHost>my-host</remoteHost>
		<port>24224</port>
		<maxQueueSize>20</maxQueueSize>
		<layout class="ch.qos.logback.classic.PatternLayout">
			<pattern>%date{HH:mm:ss.SSS} [%property{HOSTNAME}] [%thread] %-5level %logger{15}#%line %msg</pattern>
		</layout>
	</appender>
```
However, it doesn't work.
As far as I looked at DataFluentAppender implementation, there seems two problems.

- DataFluentAppender doesn't apply specified PatternLayout
- DataFluentAppender sends only specified items 
Around line 73 to 80
https://github.com/sndyuk/logback-more-appenders/blob/master/src/main/java/ch/qos/logback/more/appenders/DataFluentAppender.java

Is there any alternative solution to add hostname?

**Comment by sndyuk** [comment]
@zoosm3 
Hi,
`DataFluentAppender` can't have `layout` property since the appender transfers properties to fluentd directly.

However, you can put custom data:
https://github.com/sndyuk/logback-more-appenders/blob/master/src/test/resources/logback-appenders.xml#L38-L45

If you prefer to use logback layout instead of sending properties directly, you can use `FluentLogbackAppender `:
https://github.com/sndyuk/logback-more-appenders/blob/master/src/test/resources/logback-appenders.xml#L48-L63

I haven't tested that the `FluentLogbackAppender` can use this(`[%property{remoteHost}]`), but I believe it can...!

**Comment by zoosm3** [comment]
Hi @sndyuk,
Thanks for your reply.
I understand DataFluentAppender can't have layout. It's my configuration issue.
I'm trying another way.
